name: CI with Gradle

on: 
  push:
    branches: [ "be/**" ]
  pull_request:
    branches: [ "be/**" ]

# 워크플로우가 저장소의 콘텐츠를 읽을 수 있는 권한을 갖도록 설정
permissions: 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle
          
      - name: Make application.properties
        run: |
          cd ./be/issue-tracker/src/main
          mkdir resources
          cd resources
          touch application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties
        shell: bash

      - name: Grant execute permission for gradlew
        run: |
          cd ./be/issue-tracker
          chmod +x gradlew

      # Gradle Daemon을 사용하지 않도록 지정
      # CI 환경에서는 Daemon을 사용하지 않는 것이 일반적
      # 이유는 각 빌드가 깨끗한 환경에서 실행되며, Daemon이 이전 빌드의 상태를 유지하지 않기 때문
      - name: Run tests with Gradle
        run: |
          cd ./be/issue-tracker
          ./gradlew test --no-daemon
          
      - name: Build with Gradle
        run: |
          cd ./be/issue-tracker
          ./gradlew build -x test --no-daemon
